spring:
  datasource:
    url: jdbc:mysql://localhost:3306/repo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: hr_system_backend.mybatis.model
  configuration:
    useGeneratedKeys: true
    map-underscore-to-camel-case: true

server:
  port: 8080


